[build]
  command = "npm run build"
  publish = "dist/e-commerce/browser"

[[plugins]]
  package = "@netlify/angular-runtime"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-server-handler"
  status = 200
